st = "Cristiano Ronaldo - CR7, Scored 900 goals"
print(st,type(st))
#print(dir(str))
print(st.upper())
print(st.lower())
print(st.capitalize())
print(st.swapcase())
print(st.title())
print(st.count('o'))
print(st.join('Real Madrid'))
st2 = 'Real Madrid'
print(st2.join(st))
print(st.split(' '))
print(st.replace('Ronaldo','Messi'))
print(st.startswith('Cristiano'))
print(st.endswith('goals'))
print(st.find('Ronaldo'))
print(st.index('Ronaldo'))
print(st.isalnum())
print(st.isalpha())
print(st.isdigit())
st3 = '     CR7 is Al-Nassr Player    '
print(st3.strip())
print(st[0])
print(st[-1])
print(st[0:10])
print(st[-23:-3])
print(st[::-1])
print(reversed(st))
print(st[3::])